---
- name: Run commands on remote EOS devices and save the output
  hosts: DC_FABRIC
  connection: network_cli
  gather_facts: false
  vars:
    ansible_network_os: eos
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: run show command on remote EOS devices
      eos_command:
        commands: show lldp neighbors | json
      register: cli_output

    - name: Print LLDP neighbors
      debug:
        msg: " {{ cli_output.stdout[0] }} "

    - name: copy commands output in the save directory
      copy:
        content: "{{ cli_output.stdout[0].lldpNeighbors}}"
        dest: lldp-{{ inventory_hostname }}.json