---
- name: Create Output Folders
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Include folder info
      include_vars:
        file: folders.yml

    - name: Create Output Folders
      file:
        path: "{{item}}"
        state: directory
      loop: "{{folder}}"