---
- name: Build Switch intended CLI configuration and documentation
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: generate device intended CLI configuration and documentation
      import_role:
        name: eos_cli_config_gen