---
- name: Configuration deployment with CVP
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    # Peform config backup before config replace
    eos_config_deploy_eapi_pre_running_config_backup: true
    # Root directory where to build output structure
    root_dir: '{{ inventory_dir }}'
    # Backup directories path and filenames
    post_running_config_backup_filename: "{{ inventory_hostname }}_post_running-config.conf"
    post_running_config_backup_dir_name: 'config_backup'
    post_running_config_backup_dir: '{{ root_dir }}/{{ post_running_config_backup_dir_name }}'
    pre_running_config_backup_filename: "{{ inventory_hostname }}_pre_running-config.conf"
    pre_running_config_backup_dir_name: 'config_backup'
    pre_running_config_backup_dir: '{{ root_dir }}/{{ pre_running_config_backup_dir_name }}'
  tasks:
    - name: Containers and Configlets on CVP
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
      container_root: ‘DC1’
      configlets_prefix: ‘DC1’
      device_filter: ‘DC1’
      state: present
      execute_tasks: false