---
# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$FPNFEg4i/Fs3hMux$toS5p7WdOy8yigwY6kWivldy5td3NnEvLOREiL4WPl0kRGiMl2/6NaXChi6OboF.z19DSXAdzA6YuZF/uoMma."
  arista:
    privilege: 15
    role: network-admin
    sha512_password: "$6$BuskPpqDFXqIIQvR$FrDJaqt3gP/SdfnF8MftUAVCpyUwmxcyTYRM605NzVhFtsdE6ljtr7Fpp5YVJlVuwLVbwALTQ.DMq/HseaIou0"
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

# Cloud Vision server information
cvp_instance_ip: 192.168.0.5
cvp_ingestauth_key: key
# cvp_ingestauth_key: telarista

# OOB Management network default gateway
mgmt_gateway: 192.168.0.1

### DNS Domain ###
dns_domain: domain atd.lab

# DNS servers
name_servers:
  - 192.168.2.1
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
  - 192.168.0.1
